### ISSUE TITLE
无法上下滑动

### ISSUE THREAD

**Issue by jihongboo** [zhaoName/SwipeTableView#1]
我们的自定义cell继承SwipeTableViewCell后，整个tableview无法上下滑动，我打了断点发现，直接使用SwipeTableViewCell不会走handlePanGestureRecognizer事件，但使用继承cell时上下滑动会被handlePanGestureRecognizer方法捕捉。麻烦作者帮忙看一下是什么问题。

**Comment by zhaoName** [comment]
handlePanGestureRecognizer这个方法是处理cell的左右滑动。
而区分tableView的上下滑动 和 cell的左右滑动，是在手势的代理方法中判断的（你继承cell时有没有重写手势的代理？）,所以你可以到这里看一下。
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)gestureRecognizer

![snip20170220_1](https://cloud.githubusercontent.com/assets/16892271/23124616/ea706994-f7a8-11e6-8efa-9b2e80c21a60.png)

可能有我没考虑到的地方，有问题可以加我1452461282

**Comment by jihongboo** [comment]
我们尝试重写了UIPanGestureRecognizer的代理方法，还是不行。我发现上下滑动tableview时会触发两个不同的PanGesture事件，第一个PanGesture == self.panGesture，因此会顺利进入到条件语句中。但第二个PanGesture ！= self.panGesture，因此无法进入条件语句，返回true，tableview还是无法滑动滑动。最后我的解决方案是将PanGesture == self.panGesture替换成([gestureRecognizer isKindOfClass:[UIPanGestureRecognizer class]]，这样两次PanGesture都能进入条件语句中。

```
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)gestureRecognizer
{
    if([gestureRecognizer isKindOfClass:[UIPanGestureRecognizer class]])
    {
        if(self.editing)  return NO; //tableView在编辑状态
        
        if(self.targetOffset != 0.0) return YES; //已经在滑动状态
        
        //使UITableView可以滚动 解决滑动tableView和滑动cell冲突额问题
        CGPoint panPoint = [self.panGesture translationInView:self];
        if(fabs(panPoint.x) < fabs(panPoint.y))
        {
            for(SwipeTableCell *cell in self.tableView.visibleCells) //滑动cell时，自动隐藏swipeView
            {
                if(cell.hideSwipeViewWhenScrollCell && !cell.swipeOverlayView.hidden){
                    [cell hiddenSwipeAnimationAtCell:YES];
                }
            }
            return NO;
        }
    }
    else if(gestureRecognizer == self.tapGesture)
    {
        //解决和didSelect冲突问题
        CGPoint tapPoint = [self.tapGesture locationInView:self];
        //NSLog(@"%@,%@", NSStringFromCGRect(self.swipeOverlayView.frame), NSStringFromCGPoint(tapPoint));
        return CGRectContainsPoint(self.swipeImageView.frame, tapPoint);
    }
    return YES;
}

```
