### ISSUE TITLE
滑动后cell的复用问题

### ISSUE THREAD

**Issue by jihongboo** [zhaoName/SwipeTableView#3]
处于滑动后状态的cell会出现复用问题，因此我设置了滑动tableview时如果有cell是出于滑动后状态的话会将cell切换为正常模式。但是滑动header和footer的时候，cell无法恢复。请问有什么办法可以解决。

**Comment by zhaoName** [comment]
我更新了代码，重写了- (void)prepareForReuse方法去除重用问题。还有别的一些改动，如果你是继承的，可以重新下分代码。
